### ISSUE TITLE
SocialWall issue

### ISSUE THREAD

**Issue by travishen** [COAStatistics/aprp#35]
1. CKEditor context outer image style affect emoji
2. Mention somebody should be a clickable link
@MatsuiLin101 
![socialwall-issue-1](https://user-images.githubusercontent.com/28494579/46089478-2b1e2b80-c1e1-11e8-9af8-248112b6d3b2.png)

**Comment by MatsuiLin101** [comment]
1. image style add two attribute
    max-width: 100%;
    height: auto;
If image's width bigger than outside div, the image's width set to 100% equal to outside div.
If image's width smaller than outside div, nothing to change.
