### ISSUE TITLE
Usage of scriptLoader cause ReferenceError 

### ISSUE THREAD

**Issue by travishen** [COAStatistics/aprp#37]
**behavior**
Ajax template script loaded, JavaScript engine look at objects that not yet loaded by scriptLoader()
```
scripts = [
	// CKEditor Plugins
	"{% static 'ckeditor/ckeditor-init.js' %}",
	"{% static 'ckeditor/ckeditor/ckeditor.js' %}",
	// Masonry Plugins
	"{% static 'vendor/js/masonry.pkgd.js' %}",
	// SocialWall Plugins
	"{% static 'js/socialwall.js' %}",
]

var pagefunction = function() {
	// clears the variable if left blank
	socialWallHelper.init();
};

scriptLoader(scripts, pagefunction);
```
**fix**
```
var pagefunction = function() {
	if(window.socialWallHelper){
		socialWallHelper.init();
	}
};
```
@MatsuiLin101

**Comment by MatsuiLin101** [comment]
SocialWall render a blank form when user click socialwall link to the page.
The blank form use CKEDitor js files to render CKEDitor field but the files does not load.
So CKEDitor's js file should be load at index.html, therefore socialwall can render a blank form with CKEDitor's js files.
