### ISSUE TITLE
20181006甜柿批發東勢鎮無資料

### ISSUE THREAD

**Issue by travishen** [COAStatistics/aprp#72]
**農產品交易行情站**
![test](https://user-images.githubusercontent.com/28494579/46659497-9c99a900-cbe7-11e8-8fe1-18ffc17d71a7.png)

**aprp**
Log紀錄顯示Builder執行狀況正常

**農委會開放資料平台** #
Opendata上[查詢](http://data.coa.gov.tw/Service/OpenData/FromM/FarmTransData.aspx?$top=1000&$skip=0&StartDate=107.10.06&CropCode=z4&Market=%E6%9D%B1%E5%8B%A2)不到該筆資料，10/5同市場有資料

**Comment by MatsuiLin101** [comment]
Opendata修正API後可查詢到資料
